budget/urls.py
from django.urls import path

from . import views

app_name = 'budget'

urlpatterns = [
    path('login/', views.login_view, name='login'),

    path('', views.summary, name='summary'),

    path('signup/', views.signup, name='signup'),

    path('logout/', views.logout_view, name='logout'),

    path('expenses/', views.expense_list, name='expense_list'),

    path('expenses/recurring/', views.expense_list_recurring, name='expense_list_recurring'),

    path('expenses/record-spending/', views.record_spending, name='record_spending'),

    path('expenses/create-repeat-bill/', views.create_repeat_bill, name='create_repeat_bill'),

    path('expenses/<int:pk>/', views.expense_detail, name='expense_detail'),

    path('expenses/recurring/<int:pk>/', views.recurring_edit, name='recurring_edit'),

    path('expenses/<int:pk>/edit/', views.expense_edit, name='expense_edit'),

    path('expenses/categories/', views.category_list, name='category_list'),

]

moneyhog/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('budget/', include('budget.urls')),
]

budget/models.py
from django.db import models
from django.conf import settings
import random


class Expense(models.Model):
    expense_date = models.DateField('Date of expense')
    description = models.CharField(max_length=200, blank=True)
    category = models.ForeignKey('Category', on_delete=models.SET_NULL,null=True,blank=True)
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    receipt = models.ImageField(upload_to="images/",null=True,blank=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                            on_delete=models.CASCADE, 
                            null=False,
                            blank=False)

    def __str__(self):
        return str(self.expense_date) + " " + str(self.amount)

    def get_absolute_url(self):
        return reverse('expense_detail', kwargs={'pk': self.pk})

class RecurringExpense(models.Model):
    day = models.IntegerField('Day of expense')
    description = models.CharField(max_length=200, blank=True)
    category = models.ForeignKey('Category', on_delete=models.SET_NULL,null=True,blank=True)
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                            on_delete=models.CASCADE, 
                            null=False,
                            blank=False)


class Income(models.Model):
    date = models.DateField('Income date')
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    paycheck = models.ImageField(upload_to="images/",null=True,blank=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE, null=False,blank=False)

    def __str__(self):
        return str(self.amount) + " on " + str(self.date)

class Category(models.Model):
    name = models.CharField(max_length=50)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE, null=False,blank=False)

    def __str__(self):
        return self.name

budget/views.py
from django.shortcuts import get_object_or_404
from django.shortcuts import render
from django.shortcuts import redirect

# For working with fetch calls
from django.http import JsonResponse
import json

# Models
from django.contrib.auth.models import User
from .models import Expense
from .models import Income
from .models import Category
from .models import RecurringExpense

# Displaying success/error/etc messages
from django.contrib import messages

# Login authentication
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required

# Forms to import
from .forms import LoginForm
from .forms import AuthenticationForm
from .forms import ExpenseForm
from .forms import SearchExpensesForm
from .forms import DeleteExpenseForm
from .forms import RecurringExpenseForm
from .forms import DeleteRecurringExpenseForm
from .forms import CreateCategoryForm
from .forms import SignupForm

# For complex querying:
import operator
from functools import reduce
from django.db.models import Q
from django.db.models import Sum

# Pagination
from django.core.paginator import Paginator

# Dates
from datetime import date

# Errors 
# import logging

# Create account
def signup(request):
    if request.method == "POST":
        userForm = SignupForm(request.POST)
        if userForm.is_valid():
            user = userForm.save(commit=False)
            user.email = userForm.cleaned_data["email"]
            user.save()
            messages.success(request, "Your account was successfully created, %s! Try logging in now." % user.username)
            return redirect('budget:login')
        else:
            messages.error(request, "An error occurred and your account could not be created.")

    form = SignupForm()
    context = {
        'form': form,
    }

    return render(request, 'budget/signup.html', context)

# Login
def login_view(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('budget:summary')
        else:
            # print("user does not exist")
            messages.error(request, "Your username and/or password is incorrect.")
    # else:
    #     pass
        # Return an 'invalid login' error message.

    form = LoginForm()
    context = {
        'form': form,
    }

    return render(request, 'budget/login.html', context)

# View breakdown of spending by category and spending vs. income
@login_required
def summary(request):

    if request.method == "POST":
        post_data = json.loads(request.body)
        month = post_data['month'] # int
        year = post_data['year']   # int

        response_data = {}

        if month and year:
            first_date = str(year) + "-" + str(month) + "-01"

            # Leap years??
            month_ends = {1:31,2:28,3:31,4:30,5:31,6:30,7:31,8:31,9:30,10:31,11:30,12:31}
            second_date = str(year) + "-" + str(month) + "-" + str(month_ends[month])

            expense_date__range=[first_date, second_date]

            # Get a sum of expenses by category for the current month
            exp_by_categ = Category.objects.filter(user__exact=request.user.id).filter(expense__expense_date__range=[first_date, second_date]).annotate(sum=Sum('expense__amount')).order_by('-sum')

            # Get a sum of expenses for the current month, while
            # also building a list to send in the json response 
            #  (JS can't read python model objects)
            expenses = {}
            total_spending = 0
            for categ in exp_by_categ:
                expenses[str(categ)] = categ.sum
                total_spending += categ.sum


            # Fill out response
            response_data['result'] = 'success'
            response_data['type'] = 'current month and year'
            response_data['month'] = month
            response_data['year'] = year
            response_data['expenses'] = expenses
            response_data['total_spending'] = total_spending

        else:
            response_data['result'] = 'error'
            response_data['error'] = 'There was no month and/or year sent in the request.'

        return JsonResponse(response_data)

    else:
        # TODO: get a list of valid years for this user


        context = {
        }
        return render(request, 'budget/pie.html', context)


# Logout
@login_required
def logout_view(request):
    logout(request)
    form = LoginForm()
    context = {
        'form': form,
    }

    return render(request, 'budget/login.html', context)


# View spending history
@login_required
def expense_list(request):
    context = {}

    expenses_list = Expense.objects.filter(user__exact=request.user.id).order_by('-expense_date')
    if expenses_list:
        highest_amount = Expense.objects.order_by('-amount')[0].amount
    else:
        highest_amount = 1000

    # If a search filter call has been made, we need to filter our expenses list and create a bounded form
    if 'keywords' in request.GET:
        form = SearchExpensesForm(request.GET,user=request.user.id)
        if form.is_valid():
            keywords = form.cleaned_data["keywords"]
            date_choice = form.cleaned_data["date_choice"] 
            single_date = form.cleaned_data["single_date"]    # 04/22/2020
            date_range = form.cleaned_data["date_range"]     # 04/22/2020 - 04/22/2020
            min_amount = form.cleaned_data["min_amount"]
            max_amount = form.cleaned_data["max_amount"]
            categories = form.cleaned_data["categories"]
            has_receipt = form.cleaned_data["has_receipt"]

            context.update({'date_choice': date_choice,
                            'min_amount': min_amount,
                            'max_amount': max_amount,
                            'has_receipt': has_receipt,
                            })
            
            # Filter queryset for keywords
            if keywords:
                expenses_list = expenses_list.filter(
                    Q(expense_date__icontains=keywords) |
                    Q(amount__icontains=keywords) |
                    Q(description__icontains=keywords)
                )

            # Filter queryset for date range or single date
            # if not all_dates and use_range: # if the user selected a date range
            if date_choice == "date-range":
                # change "mm/dd/yyyy - mm/dd/yyyy"
                # into ["yyyy-mm-dd" - "yyyy-mm-dd"]
                fdl = date_range.split(" - ")[0].split('/')
                first_date = fdl[2] + "-" + fdl[0] + "-" + fdl[1]

                sdl = date_range.split(" - ")[1].split('/')
                second_date = sdl[2] + "-" + sdl[0] + "-" + sdl[1]

                expenses_list = expenses_list.filter(expense_date__range=[first_date, second_date])

            elif date_choice == "single-date":
                expenses_list = expenses_list.filter(expense_date=single_date).order_by('-expense_date')

            # Filter query set for min amount
            if min_amount and min_amount != "0.00":
                expenses_list = expenses_list.filter(amount__gte=min_amount)

            # Filter query set for max amount
            if max_amount and max_amount != "1000.00":
                expenses_list = expenses_list.filter(amount__lte=max_amount)

            # Filter query set for categories
            if categories:
                category_list = Category.objects.filter(user__exact=request.user.id)
                list_foreignid = []

                # Get a list of category primary keys (foreign keys in expense table)
                for obj in category_list:
                    if obj.name in categories:
                        list_foreignid.append(obj.id)

                # Create a list of Q objects using the category foreign keys
                q_category_list = []
                for foreignid in list_foreignid:
                    q_category_list.append(Q(category__exact=foreignid))

                expenses_list = expenses_list.filter(reduce(operator.or_, q_category_list))

            # Filter query set based on whether it has a receipt or not
            if has_receipt == "has-receipt":
                expenses_list = expenses_list.exclude(receipt__exact='')
            elif has_receipt == "no-receipt":
                expenses_list = expenses_list.filter(receipt__exact='')
        else:
            pass
            '''Need to put something here...'''
        
    else:
        form = SearchExpensesForm(request.GET,user=request.user.id)
        # form = SearchExpensesForm(request.user.id,request.GET)
        # form = SearchExpensesForm(form_kwargs={'user': request.user.id},request.GET)
        print(request.user.id)
        # form_kwargs={'user': request.user}

    limit = 10 # record limit per page
    paginator = Paginator(expenses_list, limit)
    page_number = request.GET.get('page')
    if page_number == None:
        page_number = 1
    page_obj = paginator.get_page(page_number)

    # Get total number of expenses to be displayed on the current page
    page_total = 0
    page_count = 0
    for i in page_obj:
        page_total += i.amount
        page_count += 1

    # Get the starting and ending number of expenses for the current page
    start_num = (int(page_number) - 1) * limit +1
    end_num = start_num + page_count - 1

    context.update({
        'page_obj': page_obj,
        'page_number': page_number,
        'page_total': page_total,
        'num_records': paginator.count,
        'page_range': paginator.page_range,
        'start_num' : start_num,
        'end_num': end_num,
        'form': form,
        'highest_amount': highest_amount,
    })

    # logger.info(page_number)

    return render(request, 'budget/expenses/list.html', context)

budget/templates/budget/base.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">

    <!-- Placeholder for title -->
    <title>{% block page_title %}Page Title{% endblock %}</title>

    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'budget/favicon2/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'budget/favicon2/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'budget/favicon2/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'budget/favicon2/site.webmanifest' %}">

    <!-- Bootstrap CDN -->
    <link href="https://stackpath.bootstrapcdn.com/bootswatch/4.4.1/pulse/bootstrap.min.css" rel="stylesheet" integrity="sha384-FnujoHKLiA0lyWE/5kNhcd8lfMILbUAZFAT89u11OhZI7Gt135tk3bGYVBC2xmJ5" crossorigin="anonymous">

    <!-- Font Awesome CDN -->
    <script src="https://kit.fontawesome.com/bff70a1c12.js" crossorigin="anonymous"></script>

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css2?family=Maven+Pro:wght@900&display=swap" rel="stylesheet"> 

    <!-- Stylesheets  -->
    <link rel="stylesheet" type="text/css" href="{% static 'budget/main.css' %}">

    {% block extra_styles %}{% endblock %}
    
  </head>
  <body>
    <header>
      <!-- Site Nav -->
      <nav class="navbar navbar-dark bg-primary flex just-betw align-center">
        <div class="logo flex align-center">
          <img class="nav-logo-pic mr-1" src="{% static 'budget/logo/logo-light.png' %}"> <span class="money">Money</span>Hog
        </div>
        <ul class="navbar-list flex just-betw align-end">
          <li>
              <button type="button" class="btn btn-outline-secondary hamb">
              <i class="fa fa-bars fa-lg"></i>
              </button>
          </li>
          <li class="hide">
              <a class="navbar-link {% block summary-active %}{% endblock summary-active %}" href="{% url 'budget:summary' %}"><span class="nav-icon"><i class="fas fa-chart-pie"></i></span> Summary {% block summary_active_sr %}{% endblock summary_active_sr %}</a>
          </li>
          <li class="hide">
              <a class="navbar-link {% block expenses_active %}{% endblock expenses_active %}" href="{% url 'budget:expense_list' %}"><span class="nav-icon"><i class="fas fa-receipt"></i></span> Details {% block expenses_active_sr %}{% endblock expenses_active_sr %}</a>
          </li>
          <li class="hide">
            <a class="navbar-link" href="{% url 'budget:logout' %}"><span class="nav-icon"><i class="fas fa-door-open"></i></span> Logout</a>
          </li>
        </ul>
      </nav>
   
    </header>
    <main class="wide-content">

        <!-- Placeholder for subheader -->
        {% block page-header %}
        {% endblock %}
        <div {% block main_class %}{% endblock %}>

          <!-- Messages (error, success, etc) -->
          {% if messages %}
            {% for message in messages %}
              {% if message.tags == "error" %}
              <div class="alert alert-danger alert-dismissible fade show" role="alert">
              {% else %}
              <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
              {% endif %}
              {{ message }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
            {% endfor %}
          {% endif %}

          <!-- Page Heading Title -->
          {% block page-title %}
          <div id="headingDiv" class="flex flex-wrap just-betw align-center mt-2 mb-4">
            <h1 class="imp page-title">{% block h1 %}{% endblock h1 %}</h1>
            {% block extra_button%}{% endblock extra_button %}
          </div>
          {% endblock page-title %}

          
          <!-- Placeholder for actual content -->
          {% block content %}
          {% endblock %}
        </div>
        
    </main>
    {% block footer %}{% endblock footer %}


    <!-- Bootstrap -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <!-- Nav Bar -->
    <script src="{% static '/budget/scripts/responsiveNav.js' %}"></script>
    
    <!-- Placeholder for extra scripts -->
    {% block my_scripts %}{% endblock %}

  </body>
</html>

budget/templates/budget/login.html
{% block staticload %}{% load static %}{% endblock %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">

    <!-- Placeholder for title -->
    <title>Login to MoneyHog</title>

    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'budget/favicon_io/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'budget/favicon_io/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'budget/favicon_io/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'budget/favicon_io/site.webmanifest' %}">

    <!-- Bootstrap CDN -->
    <link href="https://stackpath.bootstrapcdn.com/bootswatch/4.4.1/pulse/bootstrap.min.css" rel="stylesheet" integrity="sha384-FnujoHKLiA0lyWE/5kNhcd8lfMILbUAZFAT89u11OhZI7Gt135tk3bGYVBC2xmJ5" crossorigin="anonymous">

    <!-- Font Awesome CDN -->
    <script src="https://kit.fontawesome.com/bff70a1c12.js" crossorigin="anonymous"></script>

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css2?family=Maven+Pro:wght@900&display=swap" rel="stylesheet"> 

    <!-- Stylesheets  -->
    <link rel="stylesheet" type="text/css" href="{% static 'budget/main.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'budget/index.css' %}">
    
  </head>
  <body class="flex just-center">
    <div class="login">
        <div class="flex align-center just-center">
            <h1 class="logos flex"><img class="logo-pic mr-2" src="{% static 'budget/logo/logo.png' %}"> <span class="money">Money</span>Hog</h1>
        </div>
        <!-- <p class="">Be in control of your spending. Keep track of your spending, set budgets for yourself.</p> -->
        
        <!-- Messages -->
        {% if messages %}
          {% for message in messages %}
            {% if message.tags == "error" %}
            <div class="alert alert-danger" role="alert">
            {% else %}
            <div class="alert alert-{{ message.tags }}" role="alert">
            {% endif %}
            {{ message }}
            </div>
          {% endfor %}
        {% endif %}

        <!-- <h1 class="page-title mb-4 imp flex just-center">Login</h1> -->

        <form id="" action="{% url 'budget:login' %}" method="POST" class="inline-form" enctype="application/x-www-form-urlencoded"> 
            {% csrf_token %}
            <div class="form-group">
              <label for="{{form.username.id_for_label}}" class="title-sm">Username</label>
              {% comment %}
              <input type="" class="form-control" id="username" aria-describedby="username" placeholder="Username">
              {% endcomment %}
              {{ form.username }}
            </div>
            <div class="form-group flex flex-col">
              <label for="{{form.password.id_for_label}}" class="title-sm">Password</label>
              {{ form.password }}
              {% comment %}
              <!-- <input type="password" class="form-control" id="password" placeholder="Password"> -->
              {% endcomment %}
              <a id="forgot-pw" href="#" class="title-sm">Forgot password?</a>
            </div>
            <div class="flex flex-col">
                <button type="submit" class="btn btn-primary mb-5 imp title-med">LOGIN</button>
                <div class="flex align-center just-center">
                    <p class="mb-0 mr-3 title-sm">No Account? </p>
                    <a href="{% url 'budget:signup' %}" class="btn btn-warning imp title-sm" > Sign up</a>
              </div>
            </div>
              
        </form>
        
    </div>

  </body>
</html>

budget/templates/budget/pie.html
{% extends "budget/base.html" %}
{% load static %}

<!-- Page title -->
{% block page_title %}Budget Summary{% endblock %}

{% block extra_styles %}
<!-- Pie chart -->
<!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.3/Chart.min.js" integrity="sha512-s+xg36jbIujB2S2VKfpGmlC3T5V2TF3lY48DX7u2r9XzGzgPsa6wTpOQA7J9iffvdeBN0q9tKzRxVxw1JviZPg==" crossorigin="anonymous"></script> -->


<!-- Apex charts! -->
<script src="https://cdn.jsdelivr.net/npm/apexcharts"></script>

<link rel="stylesheet" type="text/css" href="{% static 'budget/summary.css' %}">

{% endblock %}


<!-- Income nav button is active in site nav bar -->
{% block summary-active %}navbar-active{% endblock summary-active %}
{% block summary_active_sr %}<span class="sr-only">(current)</span>{% endblock summary_active_sr %}

<!-- Spending nav bar -->
{% block pie-activ %}active{% endblock %}

<!-- Page Heading Title -->
<!-- Monthly Spending Summaries -->
{% block page-title %}
<div id="headingDiv" class="flex flex-col align-start mb-4">
    <h1 class="imp page-title"><span id="month"></span> <span id="year"></span> Summary</h1>
    <form id="" action="" method="GET" class="flex mt-2" enctype="application/x-www-form-urlencoded"> 
        {% csrf_token %}
        <!-- Viewing Month:  -->
        <div class="dropdown">
            <button id="monthDropdownButton" class="btn btn-outline-dark dropdown-toggle imp title-med mb-2" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></button>
            <div id="monthDropdown" class="dropdown-menu" aria-labelledby="chooseMonth">
                <a class="dropdown-item" href="#">January</a>
                <a class="dropdown-item" href="#">February</a>
                <a class="dropdown-item" href="#">March</a>
                <a class="dropdown-item" href="#">April</a>
                <a class="dropdown-item" href="#">May</a>
                <a class="dropdown-item" href="#">June</a>
                <a class="dropdown-item" href="#">July</a>
                <a class="dropdown-item" href="#">August</a>
                <a class="dropdown-item" href="#">September</a>
                <a class="dropdown-item" href="#">October</a>
                <a class="dropdown-item" href="#">November</a>
                <a class="dropdown-item" href="#">December</a>
            </div>
        </div>
        <div class="dropdown">
            <button id="yearDropdownButton" class="btn btn-outline-dark dropdown-toggle imp title-med mb-2" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Year</button>
            <div id="yearDropdown" class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                <a class="dropdown-item" href="#">January</a>
            </div>
        </div>
    </form>
  </div>
{% endblock page-title %}

{% block content %}
<div id="pies">
    <div id="error-message" class=""></div>
    <div class="flex flex-col align-center just-center mb-5">
        <h3 class="chart-title imp">Spending by Category</h3>
        <div id="pieSpending"></div>
    </div>
</div>

{% endblock %}



{% block footer %}
<div id="footer" class="flex just-betw">
    <a href="{% url 'budget:record_spending' %}" class="btn btn-outline-info title-lg imp block footer-btn"><i class="fas fa-plus"></i> Expense</a>
</div>

{% endblock footer %}



{% block my_scripts %}

<!-- Set current month and year in dropdown -->
<script src="{% static '/budget/scripts/summary/displayMonthYear.js' %}"></script>

<!-- Generate PIE charts -->
<script src="{% static '/budget/scripts/summary/generatePieCharts.js' %}"></script>


{% endblock %}

budget/templates/budget/signup.html
{% block staticload %}{% load static %}{% endblock %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">

    <!-- Placeholder for title -->
    <title>Signup for MoneyHog</title>

    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'budget/favicon_io/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'budget/favicon_io/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'budget/favicon_io/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'budget/favicon_io/site.webmanifest' %}">

    <!-- Bootstrap CDN -->
    <link href="https://stackpath.bootstrapcdn.com/bootswatch/4.4.1/pulse/bootstrap.min.css" rel="stylesheet" integrity="sha384-FnujoHKLiA0lyWE/5kNhcd8lfMILbUAZFAT89u11OhZI7Gt135tk3bGYVBC2xmJ5" crossorigin="anonymous">

    <!-- Font Awesome CDN -->
    <script src="https://kit.fontawesome.com/bff70a1c12.js" crossorigin="anonymous"></script>

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css2?family=Maven+Pro:wght@900&display=swap" rel="stylesheet"> 

    <!-- Stylesheets  -->
    <link rel="stylesheet" type="text/css" href="{% static 'budget/main.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'budget/index.css' %}">
    
  </head>
  <body class="flex just-center">
    <div class="login">
        <div class="flex align-center just-center">
            <h1 class="logos flex"><img class="logo-pic mr-2" src="{% static 'budget/logo/logo.png' %}"> <span class="money">Money</span>Hog</h1>
        </div>
        <!-- <p class="">Be in control of your spending. Keep track of your spending, set budgets for yourself.</p> -->
        
        <!-- Messages -->
        {% if messages %}
          {% for message in messages %}
            {% if message.tags == "error" %}
            <div class="alert alert-danger" role="alert">
            {% else %}
            <div class="alert alert-{{ message.tags }}" role="alert">
            {% endif %}
            {{ message }}
            </div>
          {% endfor %}
        {% endif %}

        <h1 class="page-title mb-4 imp flex just-center">Create a New Account</h1>

        <form id="" action="{% url 'budget:signup' %}" method="POST" class="inline-form" enctype="application/x-www-form-urlencoded"> 
            {% csrf_token %}
            <div class="form-group">
              <label for="{{form.username.id_for_label}}" class="title-sm">Username</label>
              {{ form.username }}
              <!-- <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small> -->
  
            </div>
            <div class="form-group flex flex-col">
              <label for="password1" class="title-sm">Password</label>
              {{ form.password1 }}
            </div>
            <div class="form-group flex flex-col">
            <label for="password2" class="title-sm">Confirm Password</label>
                {{ form.password2 }}
            </div>
            <div class="form-group flex flex-col mb-4">
                <label for="email" class="title-sm">Email</label>
                {{ form.email }}
                <small id="emailHelp" class="form-text text-muted">Optional, but an email address is the only way to reset your password if you forget it. We won't use it for anything else.</small>
            </div>
            <div class="flex flex-col">
                <button type="submit" class="btn btn-primary mb-4 imp title-med">SIGN UP</button>
                <div class="flex align-center just-center">
                    <p class="mb-0 mr-3 title-sm">Already have an account? </p>
                    <a href="{% url 'budget:login' %}" class="btn btn-warning imp title-sm" > Login</a>
              </div>
            </div>
              
        </form>
        
    </div>

  </body>
</html>