budget/urls.py
from django.urls import path

from . import views

app_name = 'budget'

urlpatterns = [
    path('login/', views.login_view, name='login'),

    path('', views.summary, name='summary'),

    path('signup/', views.signup, name='signup'),

    path('logout/', views.logout_view, name='logout'),

    path('expenses/', views.expense_list, name='expense_list'),

    path('expenses/recurring/', views.expense_list_recurring, name='expense_list_recurring'),

    path('expenses/record-spending/', views.record_spending, name='record_spending'),

    path('expenses/create-repeat-bill/', views.create_repeat_bill, name='create_repeat_bill'),

    path('expenses/<int:pk>/', views.expense_detail, name='expense_detail'),

    path('expenses/recurring/<int:pk>/', views.recurring_edit, name='recurring_edit'),

    path('expenses/<int:pk>/edit/', views.expense_edit, name='expense_edit'),

    path('expenses/categories/', views.category_list, name='category_list'),

]

moneyhog/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('budget/', include('budget.urls')),
]

budget/models.py
from django.db import models
from django.conf import settings
import random


class Expense(models.Model):
    expense_date = models.DateField('Date of expense')
    description = models.CharField(max_length=200, blank=True)
    category = models.ForeignKey('Category', on_delete=models.SET_NULL,null=True,blank=True)
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    receipt = models.ImageField(upload_to="images/",null=True,blank=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                            on_delete=models.CASCADE, 
                            null=False,
                            blank=False)

    def __str__(self):
        return str(self.expense_date) + " " + str(self.amount)

    def get_absolute_url(self):
        return reverse('expense_detail', kwargs={'pk': self.pk})

class RecurringExpense(models.Model):
    day = models.IntegerField('Day of expense')
    description = models.CharField(max_length=200, blank=True)
    category = models.ForeignKey('Category', on_delete=models.SET_NULL,null=True,blank=True)
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                            on_delete=models.CASCADE, 
                            null=False,
                            blank=False)


class Income(models.Model):
    date = models.DateField('Income date')
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    paycheck = models.ImageField(upload_to="images/",null=True,blank=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE, null=False,blank=False)

    def __str__(self):
        return str(self.amount) + " on " + str(self.date)

class Category(models.Model):
    name = models.CharField(max_length=50)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE, null=False,blank=False)

    def __str__(self):
        return self.name

budget/views.py
from django.shortcuts import get_object_or_404
from django.shortcuts import render
from django.shortcuts import redirect

# For working with fetch calls
from django.http import JsonResponse
import json

# Models
from django.contrib.auth.models import User
from .models import Expense
from .models import Income
from .models import Category
from .models import RecurringExpense

# Displaying success/error/etc messages
from django.contrib import messages

# Login authentication
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required

# Forms to import
from .forms import LoginForm
from .forms import AuthenticationForm
from .forms import ExpenseForm
from .forms import SearchExpensesForm
from .forms import DeleteExpenseForm
from .forms import RecurringExpenseForm
from .forms import DeleteRecurringExpenseForm
from .forms import CreateCategoryForm
from .forms import SignupForm

# For complex querying:
import operator
from functools import reduce
from django.db.models import Q
from django.db.models import Sum

# Pagination
from django.core.paginator import Paginator

# Dates
from datetime import date

# Errors 
# import logging

# Create account
def signup(request):
    if request.method == "POST":
        userForm = SignupForm(request.POST)
        if userForm.is_valid():
            user = userForm.save(commit=False)
            user.email = userForm.cleaned_data["email"]
            user.save()
            messages.success(request, "Your account was successfully created, %s! Try logging in now." % user.username)
            return redirect('budget:login')
        else:
            messages.error(request, "An error occurred and your account could not be created.")

    form = SignupForm()
    context = {
        'form': form,
    }

    return render(request, 'budget/signup.html', context)

# Login
def login_view(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('budget:summary')
        else:
            # print("user does not exist")
            messages.error(request, "Your username and/or password is incorrect.")
    # else:
    #     pass
        # Return an 'invalid login' error message.

    form = LoginForm()
    context = {
        'form': form,
    }

    return render(request, 'budget/login.html', context)

# View breakdown of spending by category and spending vs. income
@login_required
def summary(request):

    if request.method == "POST":
        post_data = json.loads(request.body)
        month = post_data['month'] # int
        year = post_data['year']   # int

        response_data = {}

        if month and year:
            first_date = str(year) + "-" + str(month) + "-01"

            # Leap years??
            month_ends = {1:31,2:28,3:31,4:30,5:31,6:30,7:31,8:31,9:30,10:31,11:30,12:31}
            second_date = str(year) + "-" + str(month) + "-" + str(month_ends[month])

            expense_date__range=[first_date, second_date]

            # Get a sum of expenses by category for the current month
            exp_by_categ = Category.objects.filter(user__exact=request.user.id).filter(expense__expense_date__range=[first_date, second_date]).annotate(sum=Sum('expense__amount')).order_by('-sum')

            # Get a sum of expenses for the current month, while
            # also building a list to send in the json response 
            #  (JS can't read python model objects)
            expenses = {}
            total_spending = 0
            for categ in exp_by_categ:
                expenses[str(categ)] = categ.sum
                total_spending += categ.sum


            # Fill out response
            response_data['result'] = 'success'
            response_data['type'] = 'current month and year'
            response_data['month'] = month
            response_data['year'] = year
            response_data['expenses'] = expenses
            response_data['total_spending'] = total_spending

        else:
            response_data['result'] = 'error'
            response_data['error'] = 'There was no month and/or year sent in the request.'

        return JsonResponse(response_data)

    else:
        # TODO: get a list of valid years for this user


        context = {
        }
        return render(request, 'budget/pie.html', context)


# Logout
@login_required
def logout_view(request):
    logout(request)
    form = LoginForm()
    context = {
        'form': form,
    }

    return render(request, 'budget/login.html', context)


# View spending history
@login_required
def expense_list(request):
    context = {}

    expenses_list = Expense.objects.filter(user__exact=request.user.id).order_by('-expense_date')
    if expenses_list:
        highest_amount = Expense.objects.order_by('-amount')[0].amount
    else:
        highest_amount = 1000

    # If a search filter call has been made, we need to filter our expenses list and create a bounded form
    if 'keywords' in request.GET:
        form = SearchExpensesForm(request.GET,user=request.user.id)
        if form.is_valid():
            keywords = form.cleaned_data["keywords"]
            date_choice = form.cleaned_data["date_choice"] 
            single_date = form.cleaned_data["single_date"]    # 04/22/2020
            date_range = form.cleaned_data["date_range"]     # 04/22/2020 - 04/22/2020
            min_amount = form.cleaned_data["min_amount"]
            max_amount = form.cleaned_data["max_amount"]
            categories = form.cleaned_data["categories"]
            has_receipt = form.cleaned_data["has_receipt"]

            context.update({'date_choice': date_choice,
                            'min_amount': min_amount,
                            'max_amount': max_amount,
                            'has_receipt': has_receipt,
                            })
            
            # Filter queryset for keywords
            if keywords:
                expenses_list = expenses_list.filter(
                    Q(expense_date__icontains=keywords) |
                    Q(amount__icontains=keywords) |
                    Q(description__icontains=keywords)
                )

            # Filter queryset for date range or single date
            # if not all_dates and use_range: # if the user selected a date range
            if date_choice == "date-range":
                # change "mm/dd/yyyy - mm/dd/yyyy"
                # into ["yyyy-mm-dd" - "yyyy-mm-dd"]
                fdl = date_range.split(" - ")[0].split('/')
                first_date = fdl[2] + "-" + fdl[0] + "-" + fdl[1]

                sdl = date_range.split(" - ")[1].split('/')
                second_date = sdl[2] + "-" + sdl[0] + "-" + sdl[1]

                expenses_list = expenses_list.filter(expense_date__range=[first_date, second_date])

            elif date_choice == "single-date":
                expenses_list = expenses_list.filter(expense_date=single_date).order_by('-expense_date')

            # Filter query set for min amount
            if min_amount and min_amount != "0.00":
                expenses_list = expenses_list.filter(amount__gte=min_amount)

            # Filter query set for max amount
            if max_amount and max_amount != "1000.00":
                expenses_list = expenses_list.filter(amount__lte=max_amount)

            # Filter query set for categories
            if categories:
                category_list = Category.objects.filter(user__exact=request.user.id)
                list_foreignid = []

                # Get a list of category primary keys (foreign keys in expense table)
                for obj in category_list:
                    if obj.name in categories:
                        list_foreignid.append(obj.id)

                # Create a list of Q objects using the category foreign keys
                q_category_list = []
                for foreignid in list_foreignid:
                    q_category_list.append(Q(category__exact=foreignid))

                expenses_list = expenses_list.filter(reduce(operator.or_, q_category_list))

            # Filter query set based on whether it has a receipt or not
            if has_receipt == "has-receipt":
                expenses_list = expenses_list.exclude(receipt__exact='')
            elif has_receipt == "no-receipt":
                expenses_list = expenses_list.filter(receipt__exact='')
        else:
            pass
            '''Need to put something here...'''
        
    else:
        form = SearchExpensesForm(request.GET,user=request.user.id)
        # form = SearchExpensesForm(request.user.id,request.GET)
        # form = SearchExpensesForm(form_kwargs={'user': request.user.id},request.GET)
        print(request.user.id)
        # form_kwargs={'user': request.user}

    limit = 10 # record limit per page
    paginator = Paginator(expenses_list, limit)
    page_number = request.GET.get('page')
    if page_number == None:
        page_number = 1
    page_obj = paginator.get_page(page_number)

    # Get total number of expenses to be displayed on the current page
    page_total = 0
    page_count = 0
    for i in page_obj:
        page_total += i.amount
        page_count += 1

    # Get the starting and ending number of expenses for the current page
    start_num = (int(page_number) - 1) * limit +1
    end_num = start_num + page_count - 1

    context.update({
        'page_obj': page_obj,
        'page_number': page_number,
        'page_total': page_total,
        'num_records': paginator.count,
        'page_range': paginator.page_range,
        'start_num' : start_num,
        'end_num': end_num,
        'form': form,
        'highest_amount': highest_amount,
    })

    # logger.info(page_number)

    return render(request, 'budget/expenses/list.html', context)

budget/templates/budget/expenses/detail.html
{% extends "budget/expenses/expense.html" %}

{% block page_title %}Expense Details{% endblock page_title %}

{% block hist-activ %}active imp{% endblock %}
{% block main_class %} class="narrow-content" {% endblock main_class %}

<!-- Page title and optional button-->
{% block h1 %}Expense #{{ expense.id }}{% endblock h1 %}
{% block extra_button %}
<button type="button" class="btn btn-danger imp title-sm" data-toggle="modal" data-target="#deleteExpense"><i class="fas fa-trash-alt"></i> Delete</button>
   
<div id="deleteExpense" class="modal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="title-xl imp">Delete Expense</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body flex just-center">
                <p class="title-xl">Are you sure you want to delete this expense?</p>
            </div>
            <div class="modal-footer flex just-around">
                <form action="{% url 'budget:expense_detail' expense.pk%}" method="POST" class="inline-form" enctype="application/x-www-form-urlencoded"> 
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger imp">Yes, delete it</button>
                </form>
                <button type="button" class="btn btn-primary imp" data-dismiss="modal">No, cancel</button>
            </div>
        </div>
    </div>
</div>
{% endblock extra_button%}
   


{% block content %}

    <table class="table mb-4">
    <tbody>
        <tr>
            <th scope="row">Date</th>
            <td>{{ expense.expense_date }}
            </td>
        </tr>
        <tr>
            <th scope="row">Amount</th>
            <td>${{ expense.amount }}    
            </td>
        </tr>
        <tr>
            <th scope="row">Category</th>
            <td>{{ expense.category }}    
            </td>
        </tr>
        <tr>
            <th scope="row">Description</th>
            <td>
                {{ expense.description }}
            </td>
        </tr>
        <tr>
            <th scope="row">Receipt </th>
            <td>
                {% if expense.receipt %} <img src="{{ expense.receipt.url }}" alt="{{ expense.receipt }}" class="w-100">
                {% endif %}
            </td>
        </tr>
    </tbody>


    </table>
    <a href="{% url 'budget:expense_edit' expense.id %}" class="btn btn-primary block imp title-med mb-3"><i class="far fa-edit"></i> Edit</a>

    {% endblock content%}

budget/templates/budget/expenses/edit-expense.html
{% extends "budget/expenses/new-spending.html" %}
{% load static %}

<!-- Set the title tag -->
{% block page_title %}Edit Expense{% endblock page_title %}

<!-- Page title and optional button-->
{% block h1 %}Edit Expense #{{ expense.id }}{% endblock h1 %}

{% block extra_button%}
<a href="{% url 'budget:expense_detail' expense.id %}" class="btn btn-info imp title-sm">Cancel</a>
{% endblock extra_button%}

<!-- Set the form action -->
{% block one-form-action %}{% url 'budget:expense_edit' expense.id %}{% endblock %}

<!-- Add a receipt if the expense has one -->
{% block existing_receipt %}
  {% if expense.receipt %}
  <span id="file-and-del" class="mb-2 flex just-center align-start w-75"> 
      <!-- <img src="{{ expense.receipt.url }}" alt="{{ expense.receipt }}" class="w-75">  -->
    <img src="../../../static/budget/walmart.png" alt="{{ expense.receipt }}" class="w-100"> 
    <button id="remove-file" type="button" class="btn btn-outline-danger del-butn"><span class="sr-only">Remove file</span><i class="fas fa-times-circle fa-2x"></i></button>
  </span>
  {% endif %}
{% endblock existing_receipt %}

<!-- Add the name to the button -->
{% block button-name %} Save Changes{% endblock %}


{% block extra-scripts %}
<!-- Function to acivate picker -->
<script src="{% static '/budget/scripts/activateDateCalendarsEdit.js' %}"></script>

<!-- Convert date for time picker so it doesn't blow up -->
<script src="{% static '/budget/scripts/convertDateForPicker.js' %}"></script>

{% endblock %}

budget/templates/budget/expenses/edit-recurring.html
{% extends "budget/expenses/new-repeat-bill.html" %}
{% load static %}

<!-- Set the title tag -->
{% block page_title %}Edit Bill{% endblock page_title %}

<!-- Page title and optional button-->
{% block h1 %}Edit Bill{% endblock h1 %}

<!-- Cancel edits -->
{% block extra_button%}
<a href="{% url 'budget:expense_list_recurring' %}" class="btn btn-info imp title-sm">Cancel</a>
{% endblock extra_button%}

<!-- Set the form action -->
{% block recur-form-action %}{% url 'budget:recurring_edit' expense.id %}{% endblock %}

<!-- Add the name to the button -->
{% block button-name %} Save Changes{% endblock %}

budget/templates/budget/expenses/expense.html
{% extends "budget/base.html" %}

<!-- Spending button is active in site nav bar -->
{% block expenses_active %}navbar-active{% endblock expenses_active %}
{% block expenses_active_sr %}<span class="sr-only">(current)</span>{% endblock expenses_active_sr %}

<!-- Spending nav bar -->
{% block page-header %}
<ul class="nav nav-pills nav-fill mb-4">
    <li class="nav-item ">
        <a class="nav-link title-med {% block hist-activ %}{% endblock %}" href="{% url 'budget:expense_list' %}"><i class="fas fa-list-ul"></i> <span class="sub-nav">History</span></a>
    </li>
    <li class="nav-item">
        <a class="nav-link title-med {% block rec-activ %}{% endblock %}" href="{% url 'budget:expense_list_recurring' %}"><i class="fas fa-redo-alt"></i> <span class="sub-nav">Repeating Bills</span></a>
    </li>
    <li class="nav-item">
        <a class="nav-link title-med {% block categ-activ %}{% endblock %}" href="{% url 'budget:category_list' %}"><i class="fas fa-tags"></i> <span class="sub-nav">Categories</span></a>
    </li>
</ul>

{% endblock %}

{% block extra_button%}
<a class="btn btn-warning title-xl imp" href="{% block link-url %}{% endblock %}"><i class="fas fa-plus"></i>  {% block btn-label %}{% endblock %}</a>
{% endblock extra_button %}

budget/templates/budget/expenses/list.html
{% extends "budget/expenses/expense.html" %}
{% load static %}
{% load bootstrap_pagination %}

{% block page_title %}Spending{% endblock page_title %}

{% block extra_styles %}
<link rel="stylesheet" type="text/css" href="{% static 'budget/list.css' %}">

<!-- Date picker -->
<link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.css" />

<!-- Amount range slider -->
<link rel="stylesheet" type="text/css" href="{% static 'budget/rangeSlider/nouislider.css' %}">

{% endblock extra_styles %}


{% block hist-activ %}active imp{% endblock %}


<!-- Page title and optional button-->
{% block h1 %}Spending History{% endblock h1 %}
{% block link-url %}{% url 'budget:record_spending' %}{% endblock %}
{% block btn-label %} Spending{% endblock %}


{% block content %}

  <div id="filters-and-list">
    <form id="filter-form" action="{% url 'budget:expense_list' %}" method="GET" class="mt-3" enctype="application/x-www-form-urlencoded"> 
      

      <div id="search-modal" class="flex just-center">
        <button id="trigger-search-modal" class="btn btn-outline-primary title-med mb-2" type="button"  aria-controls="searchFilters">
        <i class="fas fa-search"></i> Search Filters</button>
      </div>
      
      <div class="custom-modal">
        <div class="custom-modal-content">
          <div class="modal-header">
            <h5 class="modal-title imp">Search Filters</h5>
            <button id="close-modal" type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            <div id="search-section" class="mb-3">
              <label for="keywords" class="imp">Description</label>
              {{ form.keywords }}
            </div>  
        
            <div id="date-section" class="mb-3">
              <p class="imp mb-1">Date</p>
              <div class="mb-2">
                {% for radio in form.date_choice %}
                  <div class="form-check form-check-inline">
                    {{ radio.tag }}
                    <label class="form-check-label" for="{{ radio.id_for_label }}">
                      {{ radio.choice_label}}
                    </label>
                  </div>
                {% endfor %}
              </div>

              <div class="date-box flex align-center">
                {{ form.single_date }}
                {{ form.date_range }}
              </div>
            </div>
      
            <div id="amount-section" class="mb-3">  
              <p class="imp mb-3">Amount</p>  
              <div id="slider" class="mb-2"></div> 
              <div id="amount-labels" class="flex just-betw align-center date-modal-bod">
                <label for="min-amount" class="">Min</label>
                <span></span>
                <label for="max-amount" class="">Max</label>
              </div>
      
              <div id="amount-inputs" class="flex align-center just-betw date-modal-bod">
                {{ form.min_amount }}
                <span class="flex just-center" ><i class="fas fa-angle-right fa-lg"></i></span>
                {{ form.max_amount }}
              </div>
            </div>
      
            <div id="category-section" class="mb-3">
              <p class="imp mb-1">Categories</p>
              {% for category in form.categories %}
              <div class="custom-control custom-checkbox">
                {{ category.tag }}
                <label class="custom-control-label" for="{{ category.id_for_label }}">{{ category.choice_label }}</label>
              </div>
              {% endfor %}
            </div>
      
            <div id="receipt-section" class="mb-3">
              <p class="imp mb-1">Receipt</p>
              {% for radio in form.has_receipt %}
                <div class="form-check form-check-inline">
                  {{ radio.tag }}
                  <label class="form-check-label" for="{{ radio.id_for_label }}">
                    {{ radio.choice_label}}
                  </label>
                </div>
              {% endfor %}
            </div>
              
            <button type="submit" class="btn btn-outline-primary imp block"><i class="fas fa-search" aria-hidden="true"></i> Save Filters</button>
          </div>
        </div>
      </div>
    </form>
  
    {% if page_obj %}
    <div class="table-responsive flex flex-col">
      <span class="mt-2 mb-2">Showing {{ start_num }} - {{ end_num }} of {{ num_records }} expenses.</span>
      <table class="table mb-">
        <thead class="thead-light">
          <tr>
            <th scope="col" class="title-sm">ID</th>
            <th scope="col" class="title-sm">Date</th>
            <th scope="col" class="title-sm">Amount</th>
            <th scope="col" class="title-sm">Category</th>
          </tr>
        </thead>
        <tbody class="">
        
          {% for record in page_obj %}

          <tr class="click btn-link">
            <td >{{ record.pk }}</td>
            <td >{{ record.expense_date }}</td>
            <td >${{ record.amount }}</td>
            <td >{{ record.category }}</td>
          </tr>

          {% endfor %}

        </tbody>
      </table>

      <div class="flex just-center">
        {% bootstrap_paginate page_obj range=10 %}
      </div>
      
    </div>
  
    {% else %}
        <p class="mt-3 ml-3">No expenses found. Try using different search filters, or create some expenses </p>
    {% endif %}
  </div>
{% endblock content%}

{% block my_scripts %}

<!-- Declare global template variables -->
<script type="text/javascript">
  let page_number = "{{ page_number }}";
  let dateChoice = "{{ date_choice }}";
  let minAmount = "{{ min_amount }}";
  let maxAmount = "{{ max_amount }}";
  let hasReceipt = "{{ has_receipt }}";
  let highestAmount = "{{ highest_amount }}";
</script>

<!-- Makes each table row a URL -->
<script src="{% static '/budget/scripts/clickExpenseToRedirect.js' %}"></script>

<!-- Outside scripts for date and date range picker -->
<script type="text/javascript" src="https://cdn.jsdelivr.net/jquery/latest/jquery.min.js"></script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js"></script>

<!-- Activate date picker calendars -->
<script src="{% static 'budget/scripts/activateDateCalendarsSearch.js' %}"></script>

<!-- Amount range slider script from  -->
<script src="{% static '/budget/scripts/nouislider.js' %}"></script>

<!-- Add default amounts in the input fields and automatically update them as the slider moves  -->
<script src="{% static '/budget/scripts/sliderFunctions.js' %}"></script>

<!-- Disable/activate the date and date range pickers on click of the "all dates" checkbox -->
<script src="{% static '/budget/scripts/toggleActivationDatePicker.js' %}"></script>

<!-- Defaulting the appropriate search fields -->
<script src="{% static '/budget/scripts/defaultValues.js' %}"></script>

<!-- Activate custom modal -->
<script src="{% static '/budget/scripts/activateCustomModal.js' %}"></script>

{% endblock %}

budget/templates/budget/expenses/recurring-list.html
{% extends "budget/expenses/expense.html" %}
{% load static %}

{% block page_title %}Repeating Bills{% endblock page_title %}

{% block extra_styles %}
<link rel="stylesheet" type="text/css" href="{% static 'budget/rec-list.css' %}">
{% endblock extra_styles %}

{% block rec-activ %}active imp{% endblock %}

<div class="table-responsive flex flex-col">

<!-- Page title and optional button-->
{% block h1 %}Repeating Bills{% endblock h1 %}
{% block link-url %}{% url 'budget:create_repeat_bill' %}{% endblock %}
{% block btn-label %} Bill{% endblock %}

{% block content %}

    {% if recurring_expenses %}

      {% for expense in recurring_expenses %}

      {% endfor %}
    
    <span class="title-sm">Repeating bills will automatically be added to your spending history each month.</span>

    <table class="table mt-3">
      <thead class="thead-light">
        <tr>
          <th scope="col" class="title-sm">Day of the Month</th>
          <th scope="col" class="title-sm">Amount</th>
          <th scope="col" class="title-sm">Category</th>
          <th scope="col" class="title-sm">Description</th>
          <th scope="col" class="title-sm"></th>
        </tr>
      </thead>
      <tbody>        
        {% for expense in recurring_expenses %}

        <tr class="click btn-link" id="{{ expense.id }}">
          <td >{{ expense.day }}</td>
          <td >${{ expense.amount }}</td>
          <td >{{ expense.category }}</td>
          <td>{{ expense.description }}</td>
          <td>
            <button type="button" class="btn btn-outline-danger imp title-xl" data-toggle="modal" data-target="#deleteMonthlyBill{{expense.id}}"><i class="fas fa-trash-alt"></i><span class="title-sm">Delete</span>
            </button>
          </td>

          <div id="deleteMonthlyBill{{expense.id}}" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="deleteMonthlyBill{{expense.id}}" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="title-xl imp">Delete Monthly Bill</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body flex just-center">
                        <p class="title-xl">Are you sure you want to delete this monthly bill?</p>
                    </div>
                    <div class="modal-footer flex just-around">
                        <form action="{% url 'budget:recurring_edit' expense.id %}" method="POST" class="inline-form" enctype="application/x-www-form-urlencoded"> 
                            {% csrf_token %}
                            <button type="submit" class="btn btn-danger imp">Yes, delete it</button>
                        </form>
                        <button type="button" class="btn btn-primary imp" data-dismiss="modal">No, cancel</button>
                    </div>
                </div>
            </div>
          </div>

        </tr>

        {% endfor %}

      </tbody>
    </table>

        <!-- Button trigger modal -->
    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
      <i class="fas fa-trash-alt"></i>
    </button>

    <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            ...
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <button type="button" class="btn btn-primary">Save changes</button>
          </div>
        </div>
      </div>
    </div>


    {% else %}
    <p class="mb-3">You don't have any monthly bills right now. Select "Add Bill" to create some!</p>
    <h3 class="imp title-sm"><i class="fas fa-question-circle"></i> What is a monthly bill?</h3>
    <p class="">Monthly bills are any bills that you are charged the same amount for every month - rent, car payments, and insurance are great examples of monthly bills. When you create a monthly bill, we will go ahead and automatically log this bill in your spending activity every month on the day you choose.</p>
    
    {% endif %}
    
    
  </div>

{% endblock content%}

{% block my_scripts %}

<!-- Makes each table row a URL -->
<script src="../../../static/budget/scripts/clickRecurringRowToRedirect.js"></script>

<script>

</script>



{% endblock %}